[package]
name = "servo-spike"
version = "0.1.0"
edition = "2024"

[dependencies]
servo = { version = "=0.7.0", features = ["webcrypto"] }
cookie = "0.18"
dpi = "0.1"
euclid = "0.22"
url = "2.5"
image = { version = "0.25", default-features = false, features = ["png"] }

[profile.release]
debug = false
