#!/usr/bin/env bash
# Bundles Logfire's browser SDK into one self-contained ES module, montybot/static/vendor/logfire-browser.js, which
# montybot/static/telemetry.js imports. The web app has no build step: this runs only to update the SDK, and its
# output is committed. Needs Node.js (npm). Run from anywhere: scripts/vendor-logfire-browser.sh
set -euo pipefail

# The SDK, its peer dependencies, and the bundler, pinned. The output's header lists every bundled package.
PACKAGES=(
  @pydantic/logfire-browser@0.24.3
  @opentelemetry/sdk-trace-web@2.12.0
  @opentelemetry/semantic-conventions@1.43.0
  @opentelemetry/api@1.9.1
  @opentelemetry/auto-instrumentations-web@0.68.0
  logfire@0.22.10
  web-vitals@6.2.3
  esbuild@0.28.2
)

root="$(cd "$(dirname "$0")/.." && pwd)"
out="$root/montybot/static/vendor/logfire-browser.js"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
cd "$work"
npm init -y >/dev/null
npm install --no-audit --no-fund --save-exact "${PACKAGES[@]}" >/dev/null

# Without code splitting esbuild inlines the SDK's dynamic imports (auto-instrumentations, metrics, Web Vitals), so
# the result is one file with no chunks to serve.
echo "export * from '@pydantic/logfire-browser';" > entry.js
mkdir dist
npx esbuild entry.js --bundle --format=esm --platform=browser --target=es2020 --minify \
  --legal-comments=none --metafile=meta.json --outdir=dist --log-level=warning
if [ "$(ls dist)" != entry.js ]; then
  echo "esbuild wrote more than one file: $(ls dist)" >&2
  exit 1
fi
if grep -q -E '\bimport\(' dist/entry.js; then
  echo 'the bundle still imports code at run time' >&2
  exit 1
fi

node --input-type=module > header.js <<'EOF'
import { readFileSync } from 'node:fs';
const meta = JSON.parse(readFileSync('meta.json', 'utf8'));
const packages = new Set();
for (const input of Object.keys(meta.inputs)) {
  const dir = input.match(/^(.*node_modules\/(?:@[^/]+\/)?[^/]+)\//);
  if (!dir) continue;
  const { name, version, license } = JSON.parse(readFileSync(`${dir[1]}/package.json`, 'utf8'));
  packages.add(`${name}@${version} (${license})`);
}
const notice = readFileSync('node_modules/@pydantic/logfire-browser/LICENSE', 'utf8').trim();
console.log(`/*
 * Logfire's browser SDK (@pydantic/logfire-browser) and its dependencies, bundled into one ES module.
 * Generated by scripts/vendor-logfire-browser.sh: run it again to update. Do not edit.
 *
 * Bundled packages:
${[...packages].sort().map((p) => ` *   ${p}`).join('\n')}
 *
 * @pydantic/logfire-browser and logfire:
${notice.split('\n').map((line) => ` * ${line}`.trimEnd()).join('\n')}
 *
 * The OpenTelemetry packages are under the Apache License 2.0: https://www.apache.org/licenses/LICENSE-2.0
 */`);
EOF

mkdir -p "$(dirname "$out")"
cat header.js dist/entry.js > "$out"
echo "wrote $out ($(wc -c < "$out" | tr -d ' ') bytes)"
